application: record-test

version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /crossdomain.xml
  mime_type: text/xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: static/js

- url: /.*
  script: helloworld.app

libraries:
- name: jinja2
  version: latest
